config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include SimpleSearch::Model

  mapping do |i|
    i.indexes :title, boost: 1.5
    i.indexes :body, analyzer: SimpleSearch::Analyzer::Standard
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :destroy]

  def index
    @search = Post.search query_params[:query]
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create post_params
    redirect_to action: :index
  end

  def edit
  end

  def update
    @post.update_attributes post_params
    redirect_to action: :edit
  end

  def destroy
    @post.destroy
    redirect_to action: :index
  end

  private

  def find_post
    @post = Post.find params[:id].to_i
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def query_params
    params.permit(:query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def highlight_text(text, terms = [])
    if terms.present?
      text.gsub /(#{ terms.join('|')})/i do |term|
        content_tag :span, class: 'label label-warning' do
          term
        end
      end.html_safe
    end || text
  end

  def anchor_links(count)
    content_tag :ul, class: :pagination do
      count.times.map do |i|
        anchor = i + 1
        content_tag :li do
          link_to anchor.to_s, "##{anchor}"
        end
      end.join.html_safe
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "SimpleSearch"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "SimpleSearch", root_path, class: "navbar-brand"
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Posts", posts_path

    .container.fill
      .row.fill
        .col-lg
          = bootstrap_flash
          = yield

      .footer.navbar-fixed-bottom
        p.text-center &copy; SimpleSearch 2014

app/views/posts/_form.html.slim
= form_for @post, html: { class: "form form-horizontal post" } do |f|
  .form-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'form-control'
    = error_span(@post[:title])
  .form-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_area :body, :class => 'form-control', :rows => 8
    = error_span(@post[:body])
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn'

app/views/posts/edit.html.slim
- model_class = Post
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/index.html.slim
- model_class = Post
div class="page-header"
  h1 Search
= form_tag posts_path, :method => :get, class: "form form-horizontal post" do
  .input-group
      span.input-group-addon Query
      = text_field_tag :query, params[:query], :class => 'form-control'
      span.input-group-btn= submit_tag :Find, :class => 'btn btn-primary'


div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
- posts = @search.to_a
- if posts.present?
  = anchor_links posts.count
  - @search.each_with_index do |post, i|
    - anchor = i + 1
    .panel.panel-primary
      .panel-heading
        h4
          a name="#{anchor}"
          = highlight_text post.title, @search.terms
      .panel-body=highlight_text post.body, @search.terms
      .panel-footer
        = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(post), :class => 'btn btn-default'
        '
        = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_post_path, :class => 'btn btn-primary'

app/views/posts/new.html.slim
- model_class = Post
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"